import { Material } from "./types";

// Coverage is net ft² per selected package; USD sample allowances are opt-in, not supplier prices.
export const SOPREMA_MATERIALS: Material[] = [
  {
    id: "sopravapr",
    name: "SOPRAVAP’R®",
    category: "Vapor Barrier",
    productUrl: "https://www.soprema.us/products/sopravap-rr",
    dataSheetUrl:
      "https://my.assets-library.com/asset/27096eed-dbee-4607-b85d-ddcaf1772dd7/PDS-SOPRAVAP-R.pdf",
    coveragePerUnit: 468,
    thicknessMm: 0.8,
    description:
      "Self-adhering SBS-modified bitumen with a tri-laminated woven polyethylene facer.",
    composition:
      "Self-adhering SBS-modified bitumen with a tri-laminated woven polyethylene facer.",
    unit: "roll",
    pricePerUnit: null,
    samplePricePerUnit: 160,
    sourceDate: "2026-09-15",
    estimateScope: "field",
    colorHex: "#4d8dbf",
    coverageNote: "Net coverage per roll.",
    techSpecs: {
      Application: "Self-adhered",
    },
  },
  {
    id: "sopra-iso-2in-4x8",
    name: "SOPRA-ISO® · 2 in · 4 × 8 ft",
    category: "Insulation",
    productUrl: "https://www.soprema.us/products/sopra-isor",
    dataSheetUrl:
      "https://my.assets-library.com/asset/40afef80-504e-4174-a5f7-8830e05fd737/PDS-SOPRA-ISO.pdf",
    coveragePerUnit: 32,
    thicknessMm: 50.8,
    description:
      "Closed-cell polyisocyanurate foam bonded to reinforced facers.",
    composition:
      "Closed-cell polyisocyanurate foam bonded to reinforced facers.",
    unit: "board",
    pricePerUnit: null,
    samplePricePerUnit: 50,
    sourceDate: "2026-09-15",
    estimateScope: "field",
    colorHex: "#e6ce81",
    rValue: 11.4,
    techSpecs: {
      "R-value": "11.4 at 2 inches",
      "ASTM C1289": "Type II, Class 1",
    },
    environmentalEvidence: [
      {
        label: "GREENGUARD Gold",
        kind: "certification",
        validUntil: "2027-03-29",
        url: "https://my.assets-library.com/asset/b972bf08-14f4-40c1-9fd7-76122cea0610/SOPRA-ISO-GREENGUARD-Gold-Certification-2026.pdf",
      },
    ],
  },
  {
    id: "sopra-iso-plus-2in-4x8",
    name: "SOPRA-ISO PLUS® · 2 in · 4 × 8 ft",
    category: "Insulation",
    productUrl: "https://www.soprema.us/products/sopra-iso-plusr",
    dataSheetUrl:
      "https://my.assets-library.com/asset/a303aebd-eb23-4b20-a23c-38269fa274a6/PDS-SOPRA-ISO-PLUS.pdf",
    coveragePerUnit: 32,
    thicknessMm: 50.8,
    description:
      "Closed-cell polyisocyanurate foam bonded to coated reinforced glass facers.",
    composition:
      "Closed-cell polyisocyanurate foam bonded to coated reinforced glass facers.",
    unit: "board",
    pricePerUnit: null,
    samplePricePerUnit: 60,
    sourceDate: "2026-09-15",
    estimateScope: "field",
    colorHex: "#e6ce81",
    rValue: 11.4,
    techSpecs: {
      "R-value": "11.4 at 2 inches",
      "ASTM C1289": "Type II, Class 2",
    },
    environmentalEvidence: [
      {
        label: "GREENGUARD Gold",
        kind: "certification",
        validUntil: "2027-03-29",
        url: "https://my.assets-library.com/asset/b9cc315d-d4ba-4ccc-8af3-960ac5c0991f/SOPRA-ISO-PLUS-GREENGUARD-Gold-Certification-2026.pdf",
      },
    ],
  },
  {
    id: "sopraboard-quarter-4x8",
    name: "SOPRABOARD® · ¼ in · 4 × 8 ft",
    category: "Coverboard",
    productUrl: "https://www.soprema.us/products/sopraboard",
    dataSheetUrl:
      "https://my.assets-library.com/asset/e1f45a76-19b8-40d3-b524-df761d4ba60f/PDS-SOPRABOARD-1-4-IN-1-8-IN.pdf",
    coveragePerUnit: 32,
    thicknessMm: 6.35,
    description:
      "Asphalt and mineral core with fiberglass faces. Selected SKU 08423.",
    composition:
      "Asphalt and mineral core with fiberglass faces. Selected SKU 08423.",
    unit: "board",
    pricePerUnit: null,
    samplePricePerUnit: 40,
    sourceDate: "2026-09-15",
    estimateScope: "field",
    colorHex: "#685c4a",
    weightKgM2: 9.9,
  },
  {
    id: "sopralene-flam-stick",
    name: "SOPRALENE® FLAM STICK",
    category: "Base Ply",
    productUrl: "https://www.soprema.us/products/sopralener-flam-stick",
    dataSheetUrl:
      "https://my.assets-library.com/asset/a761afb2-2c21-4ee1-94fe-42291ebb15c6/PDS-SOPRALENE-FLAM-STICK.pdf",
    coveragePerUnit: 147.6,
    thicknessMm: 2.6,
    description:
      "Polyester-reinforced SBS membrane with self-adhering underside and heat-weldable upper film.",
    composition:
      "Polyester-reinforced SBS membrane with self-adhering underside and heat-weldable upper film.",
    unit: "roll",
    pricePerUnit: null,
    samplePricePerUnit: 160,
    sourceDate: "2026-09-15",
    estimateScope: "field",
    colorHex: "#454e53",
  },
  {
    id: "sopralene-flam-180",
    name: "SOPRALENE® FLAM 180",
    category: "Base Ply",
    productUrl: "https://www.soprema.us/products/sopralener-flam-180",
    dataSheetUrl:
      "https://my.assets-library.com/asset/1da79a61-878e-4b2c-86ba-6a94188db7f0/PDS-SOPRALENE-FLAM-180.pdf",
    coveragePerUnit: 98,
    thicknessMm: 3,
    description:
      "Polyester-reinforced SBS-modified bitumen membrane for heat-welded application.",
    composition:
      "Polyester-reinforced SBS-modified bitumen membrane for heat-welded application.",
    unit: "roll",
    pricePerUnit: null,
    samplePricePerUnit: 150,
    sourceDate: "2026-09-15",
    estimateScope: "field",
    colorHex: "#454e53",
  },
  {
    id: "sopralene-flam-180-fr-plus-gr",
    name: "SOPRALENE® FLAM 180 FR+ GR · WH",
    category: "Cap Sheet",
    productUrl: "https://www.soprema.us/products/sopralener-flam-180-fr-gr",
    dataSheetUrl:
      "https://my.assets-library.com/asset/48d9561b-bfc0-4d94-ac4d-917d1cab4001/PDS-SOPRALENE-FLAM-180-FR-GR.pdf",
    coveragePerUnit: 98,
    thicknessMm: 4,
    description:
      "Polyester-reinforced SBS cap sheet with ceramic granules. White SKU 01526.",
    composition:
      "Polyester-reinforced SBS cap sheet with ceramic granules. White SKU 01526.",
    unit: "roll",
    pricePerUnit: null,
    samplePricePerUnit: 190,
    sourceDate: "2026-09-15",
    estimateScope: "field",
    colorHex: "#c6c9ca",
    techSpecs: {
      "Initial SRI": "25 (WH 01526)",
      Application: "Heat-welded",
    },
  },
  {
    id: "sentinel-p150",
    name: "SENTINEL® P150 · White P302",
    category: "PVC Membrane",
    productUrl: "https://www.soprema.us/products/sentinelr-p150",
    dataSheetUrl:
      "https://my.assets-library.com/asset/297ee552-1bdf-449e-be79-7e3bc1debbb0/PDS-SENTINEL-P150.pdf",
    coveragePerUnit: null,
    thicknessMm: 1.5,
    description:
      "Polyester-reinforced PVC membrane. Selected white P302, 60 mil.",
    composition:
      "Polyester-reinforced PVC membrane. Selected white P302, 60 mil.",
    unit: "roll",
    pricePerUnit: null,
    samplePricePerUnit: 1300,
    sourceDate: "2026-09-15",
    estimateScope: "field",
    colorHex: "#eef0f0",
    coverageNote:
      "10 × 100 ft roll is gross area. Enter net coverage after laps/layout.",
    techSpecs: {
      "Initial SRI": "108",
      "Aged SRI": "90",
    },
    environmentalEvidence: [
      {
        label: "NSF/ANSI 347 Gold",
        kind: "certification",
        validUntil: "2027-12-31",
        url: "https://my.assets-library.com/asset/b8e15cdb-e844-408f-b824-f089695089c0/NSF-347-SENTINEL-PVC.pdf",
      },
    ],
  },
  {
    id: "alsan-rs-230-flash",
    name: "ALSAN® RS 230 FLASH · 12 kg",
    category: "Flashing",
    productUrl: "https://www.soprema.us/products/alsanr-rs-230-flash",
    dataSheetUrl:
      "https://my.assets-library.com/asset/aec5ce3b-5176-4ad1-8ea6-fa6dd878aaf9/PDS-ALSAN-RS-230-FLASH.pdf",
    coveragePerUnit: 40,
    thicknessMm: null,
    description: "PMMA flashing resin; separate fleece and catalyst required.",
    composition: "PMMA flashing resin; separate fleece and catalyst required.",
    unit: "pail",
    pricePerUnit: null,
    samplePricePerUnit: 320,
    sourceDate: "2026-09-15",
    estimateScope: "detail",
    colorHex: "#6e98ae",
    coverageBasis: "system",
    vocGramsPerLiter: 5,
    coverageNote:
      "40 ft² per 12 kg pail for full system on sanded base; adjust for substrate.",
    techSpecs: {
      VOC: "< 5 g/L",
    },
  },
  {
    id: "duotack-365",
    name: "DUOTACK® 365",
    category: "Adhesive/Primer",
    productUrl: "https://www.soprema.us/products/duotackr-365",
    dataSheetUrl:
      "https://my.assets-library.com/asset/f436572c-5d91-45be-910a-e880775066d3/PDS-DUOTACK-365.pdf",
    coveragePerUnit: null,
    thicknessMm: null,
    description: "Two-component polyurethane adhesive, ribbon applied.",
    composition: "Two-component polyurethane adhesive, ribbon applied.",
    unit: "cartridge",
    pricePerUnit: null,
    samplePricePerUnit: 45,
    sourceDate: "2026-09-15",
    estimateScope: "interface",
    colorHex: "#b59362",
    vocGramsPerLiter: 0,
    coverageNote:
      "Enter project coverage per cartridge from approved ribbon spacing; published range 100–150 ft².",
    techSpecs: {
      VOC: "0 g/L for each component",
    },
  },
  {
    id: "vb-01",
    name: "SOPRAVAP'R",
    category: "Vapor Barrier",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "vb-02",
    name: "SOPRAVAP® STICK SARKING",
    category: "Vapor Barrier",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "vb-03",
    name: "ELASTOPHENE® SP 3.0",
    category: "Vapor Barrier",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "vb-04",
    name: "SOPRAVAP'R LITE",
    category: "Vapor Barrier",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "in-01",
    name: "SOPRA-ISO® Polyiso Board",
    category: "Insulation",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Board (4x8)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "in-02",
    name: "SOPRA-ISO® PLUS",
    category: "Insulation",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Board (4x8)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "in-03",
    name: "SOPRA-XPS® 20",
    category: "Insulation",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Board (4x8)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "in-04",
    name: "SOPRA-XPS® 40",
    category: "Insulation",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Board (4x8)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "in-05",
    name: "SOPRA-XPS® 60",
    category: "Insulation",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Board (4x8)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "cb-01",
    name: "SOPRABOARD®",
    category: "Coverboard",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Board (4x4)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "cb-02",
    name: "PROTECT'R®",
    category: "Coverboard",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Board (4x8)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "cb-03",
    name: "SOPRA-CELLULOSE CB",
    category: "Coverboard",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Board (4x8)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "bp-01",
    name: "ELASTOPHENE® Base Sheet",
    category: "Base Ply",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "bp-02",
    name: "SOPRALENE® FLAM 180",
    category: "Base Ply",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "bp-03",
    name: "ELASTOPHENE® 180 PS",
    category: "Base Ply",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "bp-04",
    name: "COLPHENE® 3000",
    category: "Base Ply",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "bp-05",
    name: "SOPRAFIX® BASE 611",
    category: "Base Ply",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "cs-01",
    name: "SOPRALENE® FLAM 180 FR GR",
    category: "Cap Sheet",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "cs-02",
    name: "SOPRALENE® FLAM 250 FR GR",
    category: "Cap Sheet",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "cs-03",
    name: "ELASTOPHENE® FLAM FR GR",
    category: "Cap Sheet",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "cs-04",
    name: "SOPRASTAR® FLAM",
    category: "Cap Sheet",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "cs-05",
    name: "FLAGON® SR (PVC)",
    category: "Cap Sheet",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "cs-06",
    name: "FLAGON® EP/PR (TPO)",
    category: "Cap Sheet",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "cs-07",
    name: "ALSAN® RS 230 Field",
    category: "Cap Sheet",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Pail (5 Gal)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "cs-08",
    name: "ALSAN® RS 280 Field",
    category: "Cap Sheet",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Pail (5 Gal)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "cs-09",
    name: "ALSAN® COATING SIL 402",
    category: "Cap Sheet",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Pail (5 Gal)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "cs-10",
    name: "SOPRANATURE® FLAM",
    category: "Cap Sheet",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Roll",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "ad-01",
    name: "ELASTOCOL® 500 Primer",
    category: "Adhesive/Primer",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Pail (5 Gal)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "ad-02",
    name: "ELASTOCOL® 350 Primer",
    category: "Adhesive/Primer",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Pail (5 Gal)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "ad-03",
    name: "DUOTACK® Insulation Adhesive",
    category: "Adhesive/Primer",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Cartridge",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "ad-04",
    name: "DUOTACK® 365",
    category: "Adhesive/Primer",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Cartridge",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "ad-05",
    name: "COLPLY® EF Adhesive",
    category: "Adhesive/Primer",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Pail (5 Gal)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
  {
    id: "ad-06",
    name: "ALSAN® RS 222 PRIMER",
    category: "Adhesive/Primer",
    description:
      "Legacy selection: replace with a sourced catalog product or enter verified estimating inputs.",
    unit: "Pail (5 Gal)",
    coveragePerUnit: null,
    pricePerUnit: null,
    legacyOnly: true,
    colorHex: "#7C878E",
  },
];

export const ACTIVE_MATERIALS = SOPREMA_MATERIALS.filter(
  (material) => !material.legacyOnly,
);
